version: "3"

tasks:
  # ── Formatting ────────────────────────────────────────────────────────────

  fmt:
    desc: Format Swift code (swift-format)
    cmds:
      - swift-format format --in-place --recursive Sources/

  fmt:check:
    desc: Check Swift formatting without modifying files
    cmds:
      - swift-format lint --strict --recursive Sources/

  # ── Linting ───────────────────────────────────────────────────────────────

  lint:
    desc: Lint Swift code (swiftlint)
    cmds:
      - swiftlint lint --strict Sources/

  lint:fix:
    desc: Auto-fix lint issues where possible
    cmds:
      - swiftlint lint --fix Sources/

  # ── Build ─────────────────────────────────────────────────────────────────

  build:
    desc: Build the application (fmt + lint as deps)
    deps: [fmt:check, lint]
    cmds:
      - swift build

  build:release:
    desc: Build optimised release binary
    deps: [fmt:check, lint]
    cmds:
      - swift build -c release

  # ── Run ───────────────────────────────────────────────────────────────────

  dev:run:
    desc: Build and run as .app bundle (debug)
    deps: [build]
    cmds:
      - task: bundle
        vars: { CONFIG: debug }
      - open .build/PictureViewer.app

  run:
    desc: Build and run as .app bundle (release)
    deps: [build:release]
    cmds:
      - task: bundle
        vars: { CONFIG: release }
      - open .build/PictureViewer.app

  # ── App Bundle ───────────────────────────────────────────────────────────

  bundle:
    desc: Assemble .app bundle from built binary
    vars:
      CONFIG: '{{.CONFIG | default "debug"}}'
      APP: .build/PictureViewer.app
    cmds:
      - rm -rf "{{.APP}}"
      - mkdir -p "{{.APP}}/Contents/MacOS"
      - mkdir -p "{{.APP}}/Contents/Resources"
      - cp Info.plist "{{.APP}}/Contents/Info.plist"
      - cp ".build/{{.CONFIG}}/PictureViewer" "{{.APP}}/Contents/MacOS/PictureViewer"
      - cp Resources/Icons/icon.icns "{{.APP}}/Contents/Resources/icon.icns"
      - cp -R ".build/{{.CONFIG}}/PictureViewer_PictureViewer.bundle" "{{.APP}}/Contents/Resources/"

  # ── Quality Gate ──────────────────────────────────────────────────────────

  check:all:
    desc: Run all quality checks (fmt, lint, build)
    cmds:
      - task: fmt:check
      - task: lint
      - task: build

  ci:
    desc: Full CI pipeline (fmt, lint, release build)
    cmds:
      - task: fmt:check
      - task: lint
      - task: build:release

  # ── Cleanup ───────────────────────────────────────────────────────────────

  clean:
    desc: Clean build artifacts
    cmds:
      - swift package clean
      - rm -rf .build
